language: ruby
cache: bundler
rvm:
  - 2.6.3
addons:
  apt:
    packages:
      - openjdk-8-jre
before_install:
  - gem update --system
  - gem install bundler
  - nvm install node
install:
  - bundle install --jobs=3 --retry=3
  - pip install --user html5validator
  - npm install -g pa11y-ci
script:
  - bundle exec jekyll clean && bundle exec jekyll build
  - html5validator --Werror --also-check-css --also-check-svg --root _site/
  - |
    (bundle exec jekyll server -d _tmp_site & echo $! >&3) 3>jekyll.pid | grep -q 'Server running' && \
    pa11y-ci --sitemap http://localhost:4000/whiteglass/sitemap.xml && \
    kill -9 "$(cat jekyll.pid)" && \
    rm -f jekyll.pid
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  target-branch: gh-pages
  on:
    branch: master
