version: 2.1

node-environments: &node-environments
  NPM_CONFIG_PREFIX: '~/.npm-global'

node-global-path: &node-global-path
  run: echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV

node-restore-cache: &node-restore-cache
  restore_cache:
    keys:
      - npm-{{ arch }}

node-save-cache: &node-save-cache
  save_cache:
    key: npm-{{ arch }}
    paths:
      - ~/.npm
      - ~/.npm-global

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2-browsers
        environment:
          <<: *node-environments
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-{{ arch }}-{{ checksum "Gemfile" }}
            - gem-{{ arch }}-
      - run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle update
      - save_cache:
          key: gem-{{ arch }}-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - *node-global-path
      - *node-restore-cache
      - run: npm install -g pa11y-ci
      - *node-save-cache
      - run: |
          bundle exec jekyll clean
          bundle exec jekyll build
      - run: |
          (bundle exec jekyll serve -d _tmp_site --no-watch & echo $! >&3) 3>_jekyll.pid | grep -q 'Server running'
          pa11y-ci --sitemap 'http://localhost:4000/whiteglass/sitemap.xml' \
            --sitemap-find 'https://yous.github.io/whiteglass' --sitemap-replace 'http://localhost:4000/whiteglass'
          kill -9 "$(cat _jekyll.pid)"
          rm -f _jekyll.pid
          rm -rf _tmp_site
      - persist_to_workspace:
          root: .
          paths:
            - _site
  validate:
    docker:
      - image: cimg/python:3.11-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - pypi-{{ checksum "/home/circleci/.pyenv/version" }}
      - run: pip install -U html5validator
      - save_cache:
          key: pypi-{{ checksum "/home/circleci/.pyenv/version" }}
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.pyenv/versions/
            - /home/circleci/.local/lib/
      - attach_workspace:
          at: .
      - run: html5validator --Werror --also-check-css --also-check-svg --root _site/
  deploy:
    docker:
      - image: cimg/node:lts
        environment:
          <<: *node-environments
    steps:
      - checkout
      - *node-global-path
      - *node-restore-cache
      - run: npm install -g gh-pages
      - *node-save-cache
      - attach_workspace:
          at: .
      - run: |
          git config user.name "$(git --no-pager show --no-patch --format='%an')"
          git config user.email "$(git --no-pager show --no-patch --format='%ae')"
      - add_ssh_keys:
          fingerprints:
            - '96:a1:8e:89:0b:06:14:39:c3:ed:96:ee:89:49:32:c8'
      - run:
          command: gh-pages --branch gh-pages --dist _site --message "Update to ${CIRCLE_SHA1:0:7} [ci skip]"
          environment:
            CACHE_DIR: '~/.npm-global/.cache'

workflows:
  version: 2
  build:
    jobs:
      - build
      - validate:
          requires:
            - build
      - deploy:
          requires:
            - build
            - validate
          filters:
            branches:
              only: master
